version: "2"
run:
  concurrency: 4
  go: "1.24"
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errname
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - godox
    - goheader
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
    - wrapcheck
  settings:
    copyloopvar:
      check-alias: true
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
        - (*bytes.Buffer).WriteTo
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - regexpMust
    godox:
      keywords:
        - FIXME
        - BUG
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      disable:
        - fieldalignment
      enable-all: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - (or|er)$
    lll:
      line-length: 120
      tab-width: 4
    revive:
      rules:
        - name: defer
        - name: blank-imports
          disabled: true
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1004
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
        - SIP
        - RTP
        - AMQP
        - DB
        - TS
      dot-import-whitelist:
        - fmt
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    tagalign:
      align: false
      sort: true
      order:
        - db
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - form
        - validate
      strict: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: exported (type|method|function) (.+) should have comment or be unexported
      - path: (.+)\.go$
        text: 'ST1000: at least one file in a package should have a package comment'
    paths:
      - .*easyjson\.go$
      - generated
      - mocks
      - bin
      - dev
      - tests
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
      custom-order: false
      no-lex-order: false
  exclusions:
    generated: lax
    paths:
      - .*easyjson\.go$
      - generated
      - mocks
      - bin
      - dev
      - tests
      - third_party$
      - builtin$
      - examples$
output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: false
      print-linter-name: false